- hosts: localhost
  vars:
    tomee_version: 7.0.2
    tomee_distribution: plus
  tasks:
    - set_fact:
        tomee_image: jeqo/apache-tomee:{{ tomee_distribution }}-{{ tomee_version }}

    - name: building {{ tomee_image }}
      docker_image:
        name: "{{ tomee_image }}"
        path: .
        force: yes
        nocache: yes
        push: yes
      register: result

    - debug:
        var: result
